#!/bin/bash
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PREPROCESS_JOB_ID="$(sbatch --parsable slurm_jobs/dozza_three_analyses/dozza_preprocess.slurm)"
echo "Submitted preprocessing: ${PREPROCESS_JOB_ID}"

DOZZA_FLOW_H1H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_flow_h1h.slurm)"
echo "Submitted dozza_flow_h1h: ${DOZZA_FLOW_H1H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_NATIONALITY_H1H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_nationality_h1h.slurm)"
echo "Submitted dozza_nationality_h1h: ${DOZZA_NATIONALITY_H1H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_AGE_H1H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_age_h1h.slurm)"
echo "Submitted dozza_age_h1h: ${DOZZA_AGE_H1H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_FLOW_H3H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_flow_h3h.slurm)"
echo "Submitted dozza_flow_h3h: ${DOZZA_FLOW_H3H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_NATIONALITY_H3H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_nationality_h3h.slurm)"
echo "Submitted dozza_nationality_h3h: ${DOZZA_NATIONALITY_H3H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_AGE_H3H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_age_h3h.slurm)"
echo "Submitted dozza_age_h3h: ${DOZZA_AGE_H3H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_FLOW_H6H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_flow_h6h.slurm)"
echo "Submitted dozza_flow_h6h: ${DOZZA_FLOW_H6H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_NATIONALITY_H6H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_nationality_h6h.slurm)"
echo "Submitted dozza_nationality_h6h: ${DOZZA_NATIONALITY_H6H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_AGE_H6H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_age_h6h.slurm)"
echo "Submitted dozza_age_h6h: ${DOZZA_AGE_H6H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_FLOW_H12H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_flow_h12h.slurm)"
echo "Submitted dozza_flow_h12h: ${DOZZA_FLOW_H12H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_NATIONALITY_H12H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_nationality_h12h.slurm)"
echo "Submitted dozza_nationality_h12h: ${DOZZA_NATIONALITY_H12H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_AGE_H12H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_age_h12h.slurm)"
echo "Submitted dozza_age_h12h: ${DOZZA_AGE_H12H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_FLOW_H24H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_flow_h24h.slurm)"
echo "Submitted dozza_flow_h24h: ${DOZZA_FLOW_H24H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_NATIONALITY_H24H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_nationality_h24h.slurm)"
echo "Submitted dozza_nationality_h24h: ${DOZZA_NATIONALITY_H24H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"
DOZZA_AGE_H24H_JOB_ID="$(sbatch --parsable --dependency=afterok:${PREPROCESS_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_age_h24h.slurm)"
echo "Submitted dozza_age_h24h: ${DOZZA_AGE_H24H_JOB_ID} afterok:${PREPROCESS_JOB_ID}"

SUMMARY_JOB_ID="$(sbatch --parsable --dependency=afterany:${DOZZA_FLOW_H1H_JOB_ID}:${DOZZA_NATIONALITY_H1H_JOB_ID}:${DOZZA_AGE_H1H_JOB_ID}:${DOZZA_FLOW_H3H_JOB_ID}:${DOZZA_NATIONALITY_H3H_JOB_ID}:${DOZZA_AGE_H3H_JOB_ID}:${DOZZA_FLOW_H6H_JOB_ID}:${DOZZA_NATIONALITY_H6H_JOB_ID}:${DOZZA_AGE_H6H_JOB_ID}:${DOZZA_FLOW_H12H_JOB_ID}:${DOZZA_NATIONALITY_H12H_JOB_ID}:${DOZZA_AGE_H12H_JOB_ID}:${DOZZA_FLOW_H24H_JOB_ID}:${DOZZA_NATIONALITY_H24H_JOB_ID}:${DOZZA_AGE_H24H_JOB_ID} slurm_jobs/dozza_three_analyses/dozza_summary.slurm)"
echo "Submitted dozza_summary: ${SUMMARY_JOB_ID} afterany:${DOZZA_FLOW_H1H_JOB_ID}:${DOZZA_NATIONALITY_H1H_JOB_ID}:${DOZZA_AGE_H1H_JOB_ID}:${DOZZA_FLOW_H3H_JOB_ID}:${DOZZA_NATIONALITY_H3H_JOB_ID}:${DOZZA_AGE_H3H_JOB_ID}:${DOZZA_FLOW_H6H_JOB_ID}:${DOZZA_NATIONALITY_H6H_JOB_ID}:${DOZZA_AGE_H6H_JOB_ID}:${DOZZA_FLOW_H12H_JOB_ID}:${DOZZA_NATIONALITY_H12H_JOB_ID}:${DOZZA_AGE_H12H_JOB_ID}:${DOZZA_FLOW_H24H_JOB_ID}:${DOZZA_NATIONALITY_H24H_JOB_ID}:${DOZZA_AGE_H24H_JOB_ID}"
